{"uuid":"4af39ed4-c429-424a-ac44-c1aa7bd97cc5","historyId":"849efd34e0a622c1e8040b95f3a92796","fullName":"Com.tesringacdemy.tests.pageObjectModule_Test.vwo.TestVWOLogin_03_Retry.testFail","labels":[{"name":"package","value":"Com.tesringacdemy.tests.pageObjectModule_Test.vwo.TestVWOLogin_03_Retry"},{"name":"testClass","value":"Com.tesringacdemy.tests.pageObjectModule_Test.vwo.TestVWOLogin_03_Retry"},{"name":"testMethod","value":"testFail"},{"name":"parentSuite","value":"All Test Suite"},{"name":"suite","value":"C:/Users/kiran/IdeaProjects/ATB12XSeleniumAdvanceFramework"},{"name":"subSuite","value":"Com.tesringacdemy.tests.pageObjectModule_Test.vwo.TestVWOLogin_03_Retry"},{"name":"host","value":"NikKrn"},{"name":"thread","value":"16488@NikKrn.main(3)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"owner","value":"PRAMOD"}],"links":[],"name":"testFail","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [true] but found [false]","trace":"java.lang.AssertionError: expected [true] but found [false]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1590)\r\n\tat org.testng.Assert.assertTrue(Assert.java:57)\r\n\tat org.testng.Assert.assertTrue(Assert.java:67)\r\n\tat Com.tesringacdemy.tests.pageObjectModule_Test.vwo.TestVWOLogin_03_Retry.testFail(TestVWOLogin_03_Retry.java:34)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:565)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1604)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:741)\r\n\tat org.testng.TestRunner.run(TestRunner.java:616)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"Verify that invalid creds give error message","steps":[],"attachments":[{"name":"Log output","source":"0fd35df3-1be5-4dde-a135-69678e4a76ab-attachment.txt","type":"text/plain"}],"parameters":[],"start":1758383121827,"stop":1758383132517}